# Generated by Django 5.2.8 on 2025-11-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crawler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common.platformaccount', verbose_name='Account')),
            ],
            options={
                'verbose_name': 'Crawler',
                'verbose_name_plural': 'Crawlers',
            },
        ),
        migrations.CreateModel(
            name='CrawlerTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('cron_expression', models.CharField(max_length=255, verbose_name='Cron expression')),
                ('last_executed_at', models.DateTimeField(blank=True, null=True, verbose_name='Last executed at')),
                ('next_run_at', models.DateTimeField(verbose_name='Next run at')),
                ('execution_count', models.IntegerField(default=0, verbose_name='Execution count')),
                ('current_pid', models.IntegerField(blank=True, null=True, verbose_name='Current PID')),
                ('search_query', models.CharField(max_length=255, verbose_name='Search query')),
                ('crawler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crawler.crawler', verbose_name='Crawler')),
            ],
            options={
                'verbose_name': 'Crawler Task',
                'verbose_name_plural': 'Crawler Tasks',
            },
        ),
    ]
