# Generated by Django 5.2.8 on 2025-11-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crawlertask',
            name='next_run_at',
        ),
    ]
