# Generated by Django 5.2.8 on 2025-11-14 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0002_remove_crawlertask_next_run_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crawlertask',
            name='current_pid',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Current PID'),
        ),
    ]
