# Generated by Django 5.2.8 on 2025-11-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'X - (Twitter)')], verbose_name='Type')),
                ('credentials', models.JSONField(verbose_name='Credentials')),
            ],
            options={
                'verbose_name': 'Platform Account',
                'verbose_name_plural': 'Platform Accounts',
            },
        ),
    ]
